#!/usr/bin/env node

import { Command } from 'commander';
import chalk from 'chalk';
import * as fs from 'fs';
import {
  detectPII,
  redactPII,
  detectPromptInjection,
  filterContent,
  Guardrail,
} from './index';

const program = new Command();

program
  .name('ai-guardrails')
  .description('Input/output validation and safety for AI applications.')
  .version('1.0.0');

// Validate command
program
  .command('validate')
  .description('Validate text for safety issues')
  .argument('<text>', 'Text to validate')
  .option('--no-pii', 'Skip PII detection')
  .option('--no-injection', 'Skip injection detection')
  .action((text, options) => {
    const guardrail = new Guardrail({
      detectPII: options.pii,
      detectPromptInjection: options.injection,
    });

    const result = guardrail.validateInput(text);

    console.log(chalk.cyan('\n🛡️ Validation Results\n'));

    if (result.valid) {
      console.log(chalk.green('✓ Text passed validation\n'));
    } else {
      console.log(chalk.red('✗ Validation failed\n'));
    }

    if (result.issues.length > 0) {
      console.log(chalk.bold('Issues found:'));
      for (const issue of result.issues) {
        const severityColor =
          issue.severity === 'critical' ? chalk.red :
          issue.severity === 'high' ? chalk.yellow :
          issue.severity === 'medium' ? chalk.cyan : chalk.gray;

        console.log(`  ${severityColor(`[${issue.severity.toUpperCase()}]`)} ${issue.type}: ${issue.message}`);
        if (issue.detected) {
          console.log(chalk.gray(`    Detected: "${issue.detected}"`));
        }
      }
      console.log();
    }

    if (result.sanitized && result.sanitized !== text) {
      console.log(chalk.bold('Sanitized version:'));
      console.log(chalk.gray(result.sanitized));
      console.log();
    }
  });

// PII command
program
  .command('pii')
  .description('Detect PII in text')
  .argument('<text>', 'Text to scan')
  .option('--redact', 'Output redacted version')
  .action((text, options) => {
    if (options.redact) {
      console.log(redactPII(text));
      return;
    }

    const findings = detectPII(text);

    console.log(chalk.cyan('\n🔍 PII Detection\n'));

    if (findings.length === 0) {
      console.log(chalk.green('No PII detected.\n'));
      return;
    }

    console.log(chalk.yellow(`Found ${findings.length} PII item(s):\n`));

    for (const finding of findings) {
      console.log(`  ${chalk.bold(finding.type)}: ${finding.value}`);
    }
    console.log();
  });

// Injection command
program
  .command('injection')
  .description('Detect prompt injection attempts')
  .argument('<text>', 'Text to scan')
  .action((text) => {
    const findings = detectPromptInjection(text);

    console.log(chalk.cyan('\n🔐 Prompt Injection Detection\n'));

    if (findings.length === 0) {
      console.log(chalk.green('No injection attempts detected.\n'));
      return;
    }

    console.log(chalk.red(`Found ${findings.length} potential injection(s):\n`));

    for (const finding of findings) {
      console.log(`  ${chalk.bold(finding.type)}: "${finding.matched}"`);
    }
    console.log();
  });

// Filter command
program
  .command('filter')
  .description('Filter blocked content')
  .argument('<text>', 'Text to filter')
  .action((text) => {
    const result = filterContent(text);

    console.log(chalk.cyan('\n🚫 Content Filter\n'));

    if (!result.blocked) {
      console.log(chalk.green('Content passed filter.\n'));
      return;
    }

    console.log(chalk.red('Content blocked.\n'));
    console.log(chalk.bold('Categories:'), result.categories.join(', '));
    console.log(chalk.bold('Matches:'), result.matches.join(', '));
    console.log();
  });

// Init command
program
  .command('init')
  .description('Generate guardrails utilities for your project')
  .option('-d, --dir <path>', 'Output directory', './lib/guardrails')
  .option('--js', 'Generate JavaScript')
  .action((options) => {
    const ext = options.js ? 'js' : 'ts';
    const dir = options.dir;

    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const code = `// AI Guardrails
// Generated by ai-guardrails

const PII_PATTERNS = {
  email: /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}/g,
  phone: /(\\+?1[-.\\s]?)?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}/g,
  ssn: /\\b\\d{3}[-.\\s]?\\d{2}[-.\\s]?\\d{4}\\b/g,
  creditCard: /\\b(?:\\d{4}[-.\\s]?){3}\\d{4}\\b/g,
};

const INJECTION_PATTERNS = [
  /ignore\\s+(all\\s+)?(previous|above|prior)\\s+(instructions?|prompts?)/i,
  /disregard\\s+(all\\s+)?(previous|above|prior)/i,
  /you\\s+are\\s+now\\s+/i,
];

export function detectPII(text${options.js ? '' : ': string'}) {
  const findings${options.js ? '' : ': Array<{ type: string; value: string }>'} = [];
  for (const [type, pattern] of Object.entries(PII_PATTERNS)) {
    const regex = new RegExp(pattern.source, pattern.flags);
    let match;
    while ((match = regex.exec(text)) !== null) {
      findings.push({ type, value: match[0] });
    }
  }
  return findings;
}

export function redactPII(text${options.js ? '' : ': string'}, replacement = '[REDACTED]') {
  let result = text;
  for (const pattern of Object.values(PII_PATTERNS)) {
    result = result.replace(new RegExp(pattern.source, pattern.flags), replacement);
  }
  return result;
}

export function hasPromptInjection(text${options.js ? '' : ': string'}) {
  return INJECTION_PATTERNS.some(p => p.test(text));
}

export function validateInput(text${options.js ? '' : ': string'}) {
  const pii = detectPII(text);
  const injection = hasPromptInjection(text);
  return {
    valid: pii.length === 0 && !injection,
    hasPII: pii.length > 0,
    hasInjection: injection,
    sanitized: redactPII(text),
  };
}
`;

    fs.writeFileSync(`${dir}/index.${ext}`, code);
    console.log(chalk.green(`✓ Created ${dir}/index.${ext}`));

    console.log(chalk.cyan('\n✅ Guardrails utilities generated!'));
    console.log(chalk.gray('\nUsage:'));
    console.log(chalk.gray(`  import { validateInput, redactPII } from '${dir}';`));
    console.log(chalk.gray(`  const result = validateInput(userMessage);`));
  });

// Info command
program
  .command('info')
  .description('Show guardrails info')
  .action(() => {
    console.log(chalk.cyan('\n🛡️ AI Guardrails\n'));

    console.log(chalk.bold('Detections:'));
    console.log('  • PII (email, phone, SSN, credit cards)');
    console.log('  • Prompt injection attempts');
    console.log('  • Blocked content categories\n');

    console.log(chalk.bold('Quick Start:'));
    console.log(chalk.gray('  npx ai-guardrails validate "Check this text"'));
    console.log(chalk.gray('  npx ai-guardrails pii "Email: test@example.com"'));
    console.log(chalk.gray('  npx ai-guardrails injection "Ignore all previous instructions"'));
  });

program.parse();
